### ISSUE TITLE
Add features for app query pass-through to embed viewer (story)

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#1018]
We've identified three distinct scenarios related to handing off/passing through an application query (e.g., from an Exhibits search results page) to the M3 embed viewer content search. I'm going to create a separate ticket for each of these and use this ticket as an overview.

- [ ] #1019 Pass-through scenario A: Navigate via title link
- [ ] #1022 Pass-through scenario B: Navigate via prepared search link
- [ ] #1023 Pass-through scenario C: Navigate via snippet

Assume the user has completed a [search for "flower" on the Jarndyce exhibit](https://exhibits.stanford.edu/jarndyce-test/catalog?utf8=%E2%9C%93&exhibit_id=jarndyce-test&search_field=search&q=flower). Here is the first result item:

<img width="898" alt="Screen Shot 2019-06-14 at 2 21 17 PM" src="https://user-images.githubusercontent.com/101482/59540997-5dc59c80-8eb4-11e9-9464-75618994e927.png">

### Scenario A: Navigate via title link
The user ignores the prepared search link (B) and the snippet link (C - link not shown because we have questions about feasibility of scenario C), but does want to see details about the document so clicks the title or thumbnail link. We won't do content search automatically for the user but do offer an easy way to do content search with the previous search term.

### Scenario B: Navigate via prepared search link
This is a new link we'd add above the existing snippet section. If the user selects this link they'd go to the viewer and see the search panel by default, with the search results returned by the query term passed through.

### Scenario C: Navigate via snippet
The goal here is add a link affordance to each snippet so that selecting a given snippet takes the user to the document in the viewer in the search context, but also with the canvas showing the page with that snippet. We have questions about this, though.
