### ISSUE TITLE
embed: okcomputer to replace is_it_working

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#706]
Exemplar:  purl-fetcher

possibly:
- `/status` endpoint for load-balancer needs and nagios errors
- `/status/[some-dependency]` for nagios warnings;  nagios routes them to approp parties
- `/status/all-dependencies` for full dependency documentation (?)

after this
- [x] PR merged to master (#711)
- [x] deploy
  - [x] dev
  - [x] stage
  - [x] uat
  - [x] prod-a, prod-b
- [x] update Load Balancer (SAR-3261)
- [x] update nagios 
  - [x] basic checks
    - [x] dev (sul-dlss/puppet/pull/1009)
    - [x] stage (sul-dlss/puppet/pull/1008)
    - [x] uat (sul-dlss/puppet#1046)
    - [x] prod-a, prod-b (sul-dlss/puppet/pull/1065)
    - [x] embed-lb (sul-dlss/puppet/pull/1065)
  - [ ] any individual checks need separate nagios handling? (media? geo? image? web-archive-seed?)
- [ ] remove is_it_working
  - [ ] deploy
- [x] update DevOpsDocs (new nagios, load balancer ...)  (sul-dlss/DevOpsDocs#67)
