### ISSUE TITLE
Add Download option to Mirador 3 version of embed viewer (story)

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#981]
This is a story ticket for adding Download to the upcoming Mirador 3 version of the embed viewer. Specific work tickets are:

- [x] #982 Add Download menu item and Download dialog window
- [x] #983 Add download links for current canvas
- [x] #984 Add other download option links
- [x] #985 Disable Download menu item when canvas has no associated image

As an overview, here's how we're proposing to add the Download link to the Window options menu:

<img width="431" alt="Screen Shot 2019-05-16 at 1 05 59 PM" src="https://user-images.githubusercontent.com/101482/57883605-93a33280-77db-11e9-8f08-2190268b25fc.png">

And how a basic Download dialog might look:

<img width="413" alt="Screen Shot 2019-05-16 at 1 08 17 PM" src="https://user-images.githubusercontent.com/101482/57883641-b2a1c480-77db-11e9-8437-acd936ded6b6.png">

More details in the specific work tickets.
