### ISSUE TITLE
Add Share option to Mirador 3 version of embed viewer (story)

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/sul-embed#986]
This is a story ticket for adding a Share window menu option and associated dialog to the upcoming Mirador 3 version of the embed viewer. Specific work tickets are:

- [x] #987 Add Share menu item and Share dialog
- [x] #988 Add Share link section to Share dialog
- [x] #990 Add Embed section to Share dialog
- [x] #989 Add Alternative viewer section to Share dialog

As an overview, here's how we're proposing to add the Share menu item to the Window options menu:

<img width="381" alt="Screen Shot 2019-05-16 at 3 39 34 PM" src="https://user-images.githubusercontent.com/101482/57894893-a3337300-77fd-11e9-9210-dff29b81aa3e.png">

When the user selects the Share menu item, this is what the Share dialog looks like:

<img width="609" alt="Screen Shot 2019-05-17 at 8 59 41 AM" src="https://user-images.githubusercontent.com/101482/57941544-167fc800-7884-11e9-973b-06cb5558ee6c.png">

More details in the specific work tickets.

**Comment by camillevilla** [comment]
@ggeisler It seems like this has been resolved? I'm not sure what happened with the custom embed height ticket.

**Comment by ggeisler** [comment]
@camillevilla Yes, this is a story ticket and the four associated work tickets are closed so I think it makes sense to close this one. 

Technically the #990 ticket has a couple of unchecked items related to the custom size of the embed. I think we decided to add a fourth size option in lieu of the custom sizing (maybe assuming that users sophisticated enough to want a custom size might realize they could edit the actual embed code). Which seems fine to me.
